[package]
name = "haddock"
version = "0.1.0"
edition = "2021"
description = "Docker Compose for Podman"
repository = "https://github.com/seowalex/haddock"
license = "GPL-3.0-only"
keywords = ["podman", "compose", "docker", "docker-compose"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.66"
byte-unit = { version = "4.0.18", default-features = false, features = ["serde", "std"] }
clap = { version = "4.0.29", features = ["cargo", "derive"] }
dotenvy = "0.15.6"
figment = { version = "0.10.8", features = ["env"] }
humantime = "2.1.0"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
nom = "7.1.1"
once_cell = "1.16.0"
path-absolutize = "3.0.14"
parse-hyperlinks = "0.23.4"
regex = "1.7.0"
serde = { version = "1.0.151", features = ["derive"] }
serde_ignored = "0.1.5"
serde_json = "1.0.89"
serde_with = { version = "2.1.0", features = ["indexmap"] }
serde_yaml = "0.9.14"
yansi = "0.5.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
temp-env = "0.3.1"
test-generator = "0.3.1"
