[package]
name = "haddock"
version = "0.1.0"
edition = "2021"
description = "Docker Compose for Podman"

[dependencies]
anyhow = "1.0.66"
byte-unit = { version = "4.0.17", default-features = false, features = ["serde", "std"] }
clap = { version = "4.0.29", features = ["cargo", "derive"] }
humantime = "2.1.0"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
nom = "7.1.1"
parse-hyperlinks = "0.23.4"
serde = { version = "1.0.149", features = ["derive"] }
serde_ignored = "0.1.5"
serde_json = "1.0.89"
serde_with = "2.1.0"
serde_yaml = "0.9.14"
yansi = "0.5.1"

[dev-dependencies]
temp-env = "0.3.1"
test-generator = "0.3.0"
