[package]
name = "haddock"
version = "0.1.0"
edition = "2021"
description = "Docker Compose for Podman"
repository = "https://github.com/seowalex/haddock"
license = "GPL-3.0-only"
keywords = ["podman", "compose", "docker", "docker-compose"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.68"
atty = "0.2.14"
automod = "1.0.6"
byte-unit = { version = "4.0.18", default-features = false, features = ["serde", "std"] }
clap = { version = "4.1.1", features = ["cargo", "derive"] }
console = "0.15.5"
dotenvy = "0.15.6"
fastrand = "1.8.0"
figment = { version = "0.10.8", features = ["env"] }
futures = "0.3.25"
heck = "0.4.0"
hex = "0.4.3"
humantime = "2.1.0"
indexmap = { version = "1.9.2", features = ["serde"] }
indicatif = "0.17.3"
inquire = "0.5.3"
itertools = "0.10.5"
nom = "7.1.3"
once_cell = "1.17.0"
parse-hyperlinks = "0.23.4"
path-absolutize = { version = "3.0.14", features = ["once_cell_cache"] }
petgraph = "0.6.2"
regex = "1.7.1"
semver = { version = "1.0.16", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_ignored = "0.1.7"
serde_json = "1.0.91"
serde_with = { version = "2.2.0", features = ["indexmap"] }
serde_yaml = "0.9.16"
sha2 = "0.10.6"
shell-words = "1.1.0"
tokio = { version = "1.24.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["io-util", "sync"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
temp-env = "0.3.1"
test-generator = "0.3.1"
tokio-test = "0.4.2"
