[package]
name = "haddock"
version = "0.1.0"
edition = "2021"
description = "Docker Compose for Podman"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["cargo", "derive"] }
docker-compose-types = "0.2.4"
itertools = "0.10.5"
serde_json = "1.0.87"
serde_yaml = "0.9.14"
