[package]
name = "haddock"
version = "0.1.0"
edition = "2021"
description = "Docker Compose for Podman"

[dependencies]
anyhow = "1.0.66"
byte-unit = { version = "4.0.17", default-features = false, features = ["serde", "std"] }
clap = { version = "4.0.22", features = ["cargo", "derive"] }
humantime = "2.1.0"
indexmap = { version = "1.9.1", features = ["serde"] }
itertools = "0.10.5"
serde = { version = "1.0.147", features = ["derive"] }
serde_ignored = "0.1.5"
serde_json = "1.0.87"
serde_with = "2.0.1"
serde_yaml = "0.9.14"

[dev-dependencies]
glob = "0.3.0"
