[package]
name = "haddock"
version = "0.1.0"
edition = "2021"
description = "Docker Compose for Podman"

[dependencies]
clap = { version = "4.0.18", features = ["cargo", "derive"] }
serde_json = "1.0.87"
